name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jdk
        sudo apt-get install -y zlib1g-dev
        sudo apt-get install -y libncurses5-dev
        sudo apt-get install -y libncursesw5-dev
        sudo apt-get install -y libreadline6-dev
        sudo apt-get install -y libssl-dev
        sudo apt-get install -y libsqlite3-dev
        sudo apt-get install -y libgdbm-dev
        sudo apt-get install -y libbz2-dev
        sudo apt-get install -y liblzma-dev
        sudo apt-get install -y tk-dev
        sudo apt-get install -y libffi-dev
        sudo apt-get install -y libc6-dev
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer
        pip install cython
        pip install -r requirements_mobile.txt
    
    - name: Set up Android SDK
      run: |
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip commandlinetools-linux-9477386_latest.zip
        mkdir -p android-sdk/cmdline-tools
        mv cmdline-tools android-sdk/cmdline-tools/latest
        export ANDROID_HOME=$PWD/android-sdk
        export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin
        echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
        echo "PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin" >> $GITHUB_ENV
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.0"
    
    - name: Build APK
      run: |
        buildozer android debug
      env:
        ANDROID_HOME: ${{ env.ANDROID_HOME }}
        PATH: ${{ env.PATH }}
    
    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: veeva-job-scraper-apk
        path: bin/*.apk
        retention-days: 30
